### ISSUE TITLE
Thanks for sharing your code!

### ISSUE THREAD

**Issue by bodybybuddha** [crshnbrn66/PSLog#1]
Hey, there wasn't a way of contacting you via email, so I thought I just drop a note here.

I totally ripped off one of your functions in this repo - it was great!  Using it in a repo located here:[Multilog](https://github.com/bodybybuddha/MultiLogv1)

I did have to change a couple of lines to force an array - the two lines where you do get-childitem.  This was to ensure that an array was returned in case only one file existed.  Otherwise I couldn't get the script to work.

Thanks for sharing your code!

JT

**Comment by crshnbrn66** [comment]
wow Stoked that someone was able to use my Code..

**Comment by bodybybuddha** [comment]
Yeah! It's good stuff!  Keep it up - you never know who else will find it helpful!
